### PR TITLE
Some changes to bring up to date

### PR DESCRIPTION
**Pull request by Arcnor**
Hi,

I've modified your theme to be more or less up to date with what is generated by Jekyll by default right now. Specially, this makes local testing actually useful (before these changes, the `site.url` that in the case of the demo was your Github page, was being contacted all the time)

Feel free to ignore or modify before merge, of course!

### CODE REVIEW

**Comment by brianmaierjr** [comment]
And somehow I fucked this up.... any chance I could get your help?

**Comment by Arcnor** [comment]
@brianmaierjr what's does seem to be the problem?

**Comment by brianmaierjr** [comment]
http://brianmaierjr.com/long-haul/

**Comment by Arcnor** [comment]
Ok, I think the problem is that you need to specify the base path. Look in config.rb, you need to change `http_path` to `/long-haul/`, because you're not serving it at the root. Let me know if it works.

**Comment by brianmaierjr** [comment]
That makes sense but unfortunately didn't work.

**Comment by Arcnor** [comment]
I guess that as a workaround, you can also change the other `_dir` defines to include `/long-haul/`. Let me know if that works, and I'll fix the underlying cause later (a quick search for some of those variables doesn't show anything, so I guess I need to look at that doc more)

**Comment by brianmaierjr** [comment]
Hey I got it.

I needed my `baseurl` to be `/long-haul'

Thanks for all the work you did on this!

**Comment by Arcnor** [comment]
Ah, right. Sorry about that, it's been more than a month since I checked this, and I haven't touched it since :).

**Pull request merged**
